# Use control-coma instead of control-b
unbind-key C-b
set-option -g prefix 'C-,'
bind 'C-,' send-prefix

# Plugins
# After adding plugins here, do a `prefix+I` within tmux to load them
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "catppuccin/tmux"

set-option -g default-terminal "screen-256color"

# Theme
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #{window_name}"
set -g @catppuccin_window_current_text " #{window_name}"
set -g @catppuccin_date_time_format "%H:%M"
set -g @catppuccin_date_time_icon " "
set -g @catppuccin_session_icon " "
set -g status-right-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"
set -g status-position top

# Reload tmux config so we can pick up changes to this file without needing to restart tmux
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded tmux configuration!"

# Index windows from 1, not 0, so they line up a little better
# with the order of the number keys on the keyboard
set -g base-index 1
# setw -g pane-base-index 1

# Reduce the command delay time to something a bit shorter
set -sg escape-time 1
# Extend the repeat interval for repeatable commands (e.g., resize-pane)
set -sg repeat-time 1000

# Copy envars to new shells
set -g update-environment -r

# Fix clipboard services
set -g default-shell $SHELL
set -g default-command "reattach-to-user-namespace -l ${SHELL}"

# Split windows more intuitively
bind | split-window -h -c '#{pane_current_path}' # horizontal columns
bind - split-window -v -c '#{pane_current_path}' # vertical rows

# Navigate panes and windows with vim style
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Quickly jump between two windows
bind i last-window

# Resizing panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Renumber windows
bind m command-prompt -p "move window to:"  "move-window -t '%%'"

# Load local config if present
if-shell "test -f ~/.local/tmux.conf" "source-file ~/.local/tmux.conf"
if-shell "test -f ~/.tmux.conf.local" "source-file ~/.tmux.conf.local"

# Load the plugin manager
run "~/.config/tmux/plugins/tpm/tpm"
